AreaFillExampleCpp: AreaFillExampleCpp.o
	g++ -o AreaFillExampleCpp AreaFillExampleCpp.o -ldebug -lamiga
AreaFillExampleCpp.o: AreaFillExampleCpp.cpp
	g++ -o AreaFillExampleCpp.o -c AreaFillExampleCpp.cpp
